name: "CI"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: CI Test
    # https://github.com/actions/virtual-environments/
    runs-on: ubuntu-latest
    steps:

      - name: Install dependencies 🔧
        run: sudo apt-get install flake8
      # https://github.com/hashicorp/setup-terraform
      - uses: hashicorp/setup-terraform@v4

      - name: 🛎️ Checkout
        uses: actions/checkout@v6

      # Check Python scripts
      - name: Python 🔎
        run: flake8 --ignore=W292 --max-line-length=127 --show-source --statistics *.py

      # Check Terraform
      - name: Terraform 🔎
        run: terraform init && terraform validate && terraform fmt -check